default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: 1234
  host: localhost

development:
  <<: *default
  database: qlda_development

test:
  <<: *default
  database: qlda_test

production:
  <<: *default
  database: ENV['DATABASE_URL']
  username: ENV['CLEARDB_DATABASE_USERNAME']
  password: ENV['CLEARDB_DATABASE_PASSWORDs']
